controllers/BlogController.php
<?php

namespace app\controllers;


use app\models\BlogForm;
use app\models\Comments;
use app\models\Profile;
use yii\web\UploadedFile;
use app\models\Blogs;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use Yii;

class BlogController extends Controller
{

    public function actionViewBlog($id = null){
        if(is_null($id)){
            $id = Yii::$app->user->identity->getId();
        }

        $profile = Profile::findOne(['user_id' => $id]);

        $avatar = $profile->getDefaultAvatar();

        if ($profile === null) {
            throw new NotFoundHttpException();
        }

        $blogs = Blogs::find()->where(['author_id' => $id]);

        $dataProvider = new ActiveDataProvider([
            'query' => $blogs,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'defaultOrder' => [
                    'datetime' => SORT_DESC,
                ]
            ],
        ]);
        $owner = null;

        if(\Yii::$app->user->identity->getId() == $id) {
            $owner = true;
        }

        elseif (\Yii::$app->user->identity->getId() != $id){
            $owner = false;
        }
        return $this->render('viewBlog', [
            'model' => $profile,
            'avatar' => $avatar,
            'dataProvider' => $dataProvider,
            'owner' => $owner
        ]);

    }

    public function actionCreate(){

        $blog = new BlogForm();

        if($blog->load(Yii::$app->request->post())){
            $blog->images = UploadedFile::getInstances($blog, 'images');
            $blog->save();
            $this->redirect(['view-blog']);
        }

        return $this->render('create',[
            'model' => $blog
        ]);

    }

    public function actionView($bid){

        $comment = new Comments;

        if($comment->load(Yii::$app->request->post())){
            $comment->blog_id = $bid;
            $comment->date_com = time();
            $comment->author_com = Yii::$app->user->identity->getId();
            $comment->save();
            $comment->refresh();
        }

        $blog = Blogs::find()->joinWith(['author', 'pictures', 'comments'])->where(['blogs.blog_id' => $bid])->one();

        $avatar = $blog->author->getDefaultAvatar();

        return $this->render('view', [
            'blog' => $blog,
            'comment' => $comment,
            'avatar' => $avatar
        ]);
    }

    public function actionEdit($bid){

        $blog = Blogs::findOne(['blog_id' => $bid]);

        if($blog->load(Yii::$app->request->post())){
            $blog->update();
            $this->redirect(['view-blog']);
        }

        return $this->render('editBlog', [
           'blog' => $blog
        ]);

    }

    public function actionDelete($bid){
        if($bid){
            $blog = Blogs::findOne(['blog_id' => $bid]);
            $blog->delete();
            return true;
        }
        else{
            return false;
        }

    }

}

controllers/NewsController.php
<?php

namespace app\controllers;


use app\models\Blogs;
use yii\data\ActiveDataProvider;
use yii\web\Controller;

class NewsController extends Controller
{

    public function actionIndex(){

        $news = Blogs::find()->joinWith(['author', 'pictures']);

        $dataProvider = new ActiveDataProvider([
           'query' => $news,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'defaultOrder' => [
                    'datetime' => SORT_DESC,
                ]
            ],
        ]);



        return $this->render('index',[
            'dataProvider' => $dataProvider
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Hello Blog!',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Профіль', 'url' => ['/blog/view-blog']],
            ['label' => 'Новини', 'url' => ['/news/index']],
            ['label' => 'Налаштування', 'url' => ['/user/settings']],
            Yii::$app->user->isGuest ?
                ['label' => 'Sign in', 'url' => ['/user/security/login']] :
                ['label' => 'Sign out (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/user/security/logout'],
                    'linkOptions' => ['data-method' => 'post']],
            ['label' => 'Register', 'url' => ['/user/registration/register'], 'visible' => Yii::$app->user->isGuest]
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>