models/BlogForm.php
<?php

namespace app\models;


use yii\base\Model;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use Yii;

class BlogForm extends Model
{
    public $title;
    public $text;
    public $images;
    public $commenting;

    public function rules() {
        return [
            [['title', 'text'], 'required'],
            ['title', 'string', 'min' => 1, 'max' => 255, 'message' => 'Неприпустима кількість символів'],
            [['images'], 'file', 'extensions' => 'png, jpg', 'maxFiles' => 0],
            ['commenting', 'number', 'min' => 0, 'max' => 1]
        ];
    }

    public function uploads(){
        if ($this->validate()) {
            $pathToFile = 'uploads/images/'. Yii::$app->user->identity->getId();
            if(!is_dir($pathToFile)){
                FileHelper::createDirectory($pathToFile, 0755);
            }
            foreach ($this->images as $file) {
                $file->saveAs($pathToFile . '/' . $file->baseName . '.' . $file->extension);
            }
            return true;
        } else {
            return false;
        }
    }

    public function save(){
        if ($this->validate()) {

            $datetime = time();

            $blog = new Blogs();
//            $blog->attributes = $this;
            $blog->title = $this->title;
            $blog->text = $this->text;
            $blog->author_id = Yii::$app->user->identity->getId();
            $blog->datetime = $datetime;
            $blog->commenting = $this->commenting;

            $blog->save();

            $this->uploads();

            $cnt = 0;
            foreach ($this->images as $file) {
                $image = new Pictures();
                $image->blog_id = $blog->blog_id;
                $image->author_id = Yii::$app->user->identity->getId();
                $image->src = $file->baseName . '.' . $file->extension;
                if($cnt == 0){
                    $image->promo = 1;
                } else {
                    $image->promo = 0;
                }
                $cnt++;

                $image->save();

            }

        }
        else {
            return false;
        }

        return true;

    }



}

models/Blogs.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "blogs".
 *
 * @property integer $blog_id
 * @property string $title
 * @property string $text
 * @property integer $author_id
 * @property integer $datetime
 * @property integer $commenting
 *
 * @property Profile $author
 * @property Comments[] $comments
 * @property Pictures[] $pictures
 */
class Blogs extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blogs';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['author_id', 'datetime', 'commenting'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['text'], 'string'],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => Profile::className(), 'targetAttribute' => ['author_id' => 'user_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'blog_id' => Yii::t('app', 'Blog ID'),
            'title' => Yii::t('app', 'Title'),
            'text' => Yii::t('app', 'Text'),
            'author_id' => Yii::t('app', 'Author'),
            'datetime' => Yii::t('app', 'Datetime'),
            'commenting' => Yii::t('app', 'Commenting'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Profile::className(), ['user_id' => 'author_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comments::className(), ['blog_id' => 'blog_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPictures()
    {
        return $this->hasMany(Pictures::className(), ['blog_id' => 'blog_id']);
    }
}

controllers/BlogController.php
<?php

namespace app\controllers;


use app\models\BlogForm;
use app\models\Comments;
use app\models\Profile;
use yii\web\UploadedFile;
use app\models\Blogs;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use Yii;

class BlogController extends Controller
{

    public function actionViewBlog($id = null){
        if(is_null($id)){
            $id = Yii::$app->user->identity->getId();
        }

        $profile = Profile::findOne(['user_id' => $id]);

        $avatar = $profile->getDefaultAvatar();

        if ($profile === null) {
            throw new NotFoundHttpException();
        }

        $blogs = Blogs::find()->where(['author_id' => $id]);

        $dataProvider = new ActiveDataProvider([
            'query' => $blogs,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'defaultOrder' => [
                    'datetime' => SORT_DESC,
                ]
            ],
        ]);
        $owner = null;

        if(\Yii::$app->user->identity->getId() == $id) {
            $owner = true;
        }

        elseif (\Yii::$app->user->identity->getId() != $id){
            $owner = false;
        }
        return $this->render('viewBlog', [
            'model' => $profile,
            'avatar' => $avatar,
            'dataProvider' => $dataProvider,
            'owner' => $owner
        ]);

    }

    public function actionCreate(){

        $blog = new BlogForm();

        if($blog->load(Yii::$app->request->post())){
            $blog->images = UploadedFile::getInstances($blog, 'images');
            $blog->save();
            $this->redirect(['view-blog']);
        }

        return $this->render('create',[
            'model' => $blog
        ]);

    }

    public function actionView($bid){

        $comment = new Comments;

        if($comment->load(Yii::$app->request->post())){
            $comment->blog_id = $bid;
            $comment->date_com = time();
            $comment->author_com = Yii::$app->user->identity->getId();
            $comment->save();
            $comment->refresh();
        }

        $blog = Blogs::find()->joinWith(['author', 'pictures', 'comments'])->where(['blogs.blog_id' => $bid])->one();

        $avatar = $blog->author->getDefaultAvatar();

        return $this->render('view', [
            'blog' => $blog,
            'comment' => $comment,
            'avatar' => $avatar
        ]);
    }

    public function actionEdit($bid){

        $blog = Blogs::findOne(['blog_id' => $bid]);

        if($blog->load(Yii::$app->request->post())){
            $blog->update();
            $this->redirect(['view-blog']);
        }

        return $this->render('editBlog', [
           'blog' => $blog
        ]);

    }

    public function actionDelete($bid){
        if($bid){
            $blog = Blogs::findOne(['blog_id' => $bid]);
            $blog->delete();
            return true;
        }
        else{
            return false;
        }

    }

}

views/blog/create.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\widgets\FileInput;
//use Yii;

$this->title = 'Створити новий запис';
?>



<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

<?= $form->field($model, 'title')->textInput(['placeholder' => 'Заголовок']) ?>
<?= $form->field($model, 'text')->textarea(['rows' => 12, 'placeholder' => 'Зміст']) ?>
<?= $form->field($model, 'images[]')->widget(FileInput::classname(), ['options' => ['accept' => 'image/*', 'multiple' => true]]) ?>
<?= $form->field($model, 'commenting')->checkbox() ?>

<?= Html::submitButton('Зберегти', ['class' => 'btn btn-success']) ?>

<?= Html::a('Повернутись', Url::to(['/blog/view-blog']), ['class' => 'btn btn-default']) ?>

<?php ActiveForm::end(); ?>

views/blog/editBlog.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = "Редагування запису";

?>

<?php $form = ActiveForm::begin() ?>

<?= $form->field($blog, 'title')->textInput(['placeholder' => 'Заголовок']) ?>

<?= $form->field($blog, 'text')->textarea(['placeholder' => 'Зміст']) ?>

<?= Html::submitButton('Зберегти зміни', ['class' => 'btn btn-success'])?>

<?php ActiveForm::end(); ?>

views/blog/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\assets\CommentAsset;
use app\assets\GalleryAsset;

CommentAsset::register($this);
GalleryAsset::register($this);

?>

<div class="row">
    <div class="span8">
        <div class="row">
            <div class="span8">
                <h4><strong><?= $blog['title'] ?></strong></h4>
            </div>
        </div>
        <div class="row">
            <span class="col-md-2">
                <a href="#" class="author">
                    <img src="<?= $avatar ?>" alt="" width="200px">
                    <p class="author_post"><b><?= $blog->author->user->username ?></b></p>
                </a>
            </span>
            <span class="col-md-8">
                <?= Html::a('<span class="glyphicon glyphicon-trash"></span>', Url::to(['/blog/delete', 'bid' => $blog->blog_id]), ['title' => Yii::t('app', 'видалити запис')]); ?>
                <?= Html::a('<span class="glyphicon glyphicon-pencil"></span>', Url::to(['/blog/edit', 'bid' => $blog->blog_id]), ['title' => Yii::t('app', 'редагувати запис')]); ?>
                <p>
                    <?= $blog['text'] ?>
                </p>
            </span>
        </div>
        <div class="col-md-offset-3">
            <?php if(!empty($blog->pictures)) : ?>
                <div class="galleria">
                    <?php foreach($blog->pictures as $picture) : ?>
                        <img src="<?= Url::to(['/web/uploads/images/'.$blog['author_id'].'/'.$picture['src']]) ?>" data-title="My title" data-description="My description">
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
        <hr>
        <?php if($blog['commenting']) : ?>
        <div class="comments">
            <div class="col-md-12">
                <?php if(!empty($blog->comments)) : ?>
                <?php foreach($blog->comments as $comment) :
                    if($comment->answer) : ?>
                       <div class="col-md-8">
                           <?= $comment->text ?>
                       </div>

                    <?php else : ?>
                        <div class="col-md-10">
                            <span class="col-md-2">
                                <div>
                                    <?= $comment->authorCom->user->username ?>
                                </div>
                                <div>
                                    <?= date('F j, Y, H:m', $comment->date_com) ?>
                                </div>
                            </span>
                            <span class="col-md-10">
                                <?= $comment->text ?>
                            </span>

                       </div>
                    <?php endif; ?>
                        <div class="row">
                            <?= Html::a('Відповісти', '#', ['id' => 'add_answer']) ?>
                        </div>

                <?php endforeach; ?>
                <?php else : ?>
                    <div class="col-md-8">
                        <?= Yii::t('app', 'Цей запис ще не коментували') ?>
                    </div>
                <?php endif; ?>
            </div>
            <?php $form = ActiveForm::begin([
                'id' => 'form_comment',
                'options' => ['class' => 'c-profileForm form-horizontal'],
                'fieldConfig' => [
                    'template' => "{input}<div>{error}\n{hint}</div>",
                    'options' => [
                        'tag' => false],
                ],
            ]); ?>
                <?= $form->field($comment, 'text')->textarea(['placeholder' => 'Ваш коментар...']); ?>
                <?= $form->field($comment, 'answer')->textInput(['id'=>'answer','type' => 'hidden']); ?>

                <?= Html::submitButton('Додати', ['class' => 'btn btn-success']) ?>

            <?php ActiveForm::end(); ?>
            <div class="row">
                <?= Html::a('Додати коментар', '#', ['id' => 'add_comment']) ?>
            </div>
        </div>
        <?php else : ?>
            <div class="col-md-8">
                <?= Yii::t('app', 'Для цього запису відключена можливість коментування') ?>
            </div>
        <?php endif; ?>
    </div>
</div>

views/blog/viewBlog.php
<?php


use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ListView;

/**
 * @var \yii\web\View $this
 * @var \dektrium\user\models\Profile $profile
 */

$this->title = empty($model->user->username) ? Html::encode($profile->user->username) : Html::encode($model->user->username);
$this->params['breadcrumbs'][] = $this->title;

$this->registerCssFile('/css/profile.css');
?>
<div class="row">
    <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="row">
            <div class="col-sm-6 col-md-7">
                <?= Html::img($avatar, [
                    'class' => 'img-rounded c-user_img',
                    'id' => 'usr_img',
//                    'alt' => $this->params['profile']->username,
                    'width' => 200
                ]) ?>
                <p class="username"><b><?= $model->user->username ?></b></p>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <?= Html::a('Створити запис', Url::to(['/blog/create']), ['class' => 'btn btn-success'])?>

        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '/_blogs',
        ]); ?>
    </div>
</div>